{
 "title": "Block Processing Performance",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Block Processing Total Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(block_processing_times_sum[5m])\n/\nrate(block_processing_times_count[5m])"
    }
   ]
  },
  {
   "title": "Block Processing DB Read",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(block_processing_db_read_times_sum[5m])\n/\nrate(block_processing_db_read_times_count[5m])"
    }
   ]
  },
  {
   "title": "Block Processing Committee Times",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(block_processing_committee_building_times_sum[5m])\n/\nrate(block_processing_committee_building_times_count[5m])"
    }
   ]
  },
  {
   "title": "Block Processing DB Write",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(block_processing_db_write_times_sum[5m])\n/\nrate(block_processing_db_write_times_count[5m])"
    }
   ]
  },
  {
   "title": "Block Processing Core-Processing Times",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(block_processing_core_times_sum[5m])\n/\nrate(block_processing_core_times_count[5m])"
    }
   ]
  },
  {
   "title": "Block Processing State Hashing Times",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(block_processing_state_root_times_sum[5m])\n/\nrate(block_processing_state_root_times_count[5m])"
    }
   ]
  },
  {
   "title": "Block Processing Fork Choice Register Times",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(block_processing_fork_choice_register_times_sum[5m])\n/\nrate(block_processing_fork_choice_register_times_count[5m])"
    }
   ]
  },
  {
   "title": "Block Processing Find Head",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(block_processing_fork_choice_find_head_times_sum[5m])\n/\nrate(block_processing_fork_choice_find_head_times_count[5m])"
    }
   ]
  }
 ]
}