{
 "title": "Consensus",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Present Slot",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "present_slot" }
   ]
  },
  {
   "title": "Best Slot Lag",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "present_slot - best_slot" }
   ]
  },
  {
   "title": "Epochs Since Finality",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "present_epoch - finalized_epoch - 1"
    }
   ]
  },
  {
   "title": "Epochs Since Justification",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "present_epoch - justified_epoch - 1"
    }
   ]
  },
  {
   "title": "Total Validator Balances",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "ETH" }
   ],
   "targets": [
    {
     "expr": "validator_balances_sum / 1000000000"
    }
   ]
  },
  {
   "title": "Blocks Processed",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "block_processing_requests" }
   ]
  },
  {
   "title": "Invalid Blocks (Total)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "block_processing_requests - block_processing_successes"
    }
   ]
  },
  {
   "title": "Block Processing Times (5 min avg.)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(block_processing_times_sum[5m])\n/\nrate(block_processing_times_count[5m])"
    }
   ]
  },
  {
   "title": "Fork Choice `find_head` Run Times",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(fork_choice_time_sum[5m])\n/\nrate(fork_choice_time_count[5m])"
    }
   ]
  },
  {
   "title": "Fork Choice Changed Head Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "fork_choice_changed_head" }
   ]
  },
  {
   "title": "Attestations Processed",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "attestation_processing_requests"
    }
   ]
  },
  {
   "title": "Invalid Attestations",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "attestation_processing_requests - attestation_processing_successes"
    }
   ]
  },
  {
   "title": "Attestation Processing Times",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(attestation_processing_times_sum[5m])\n/\nrate(attestation_processing_times_count[5m])"
    }
   ]
  },
  {
   "title": "Attestations per Block (5m avg.)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(operations_per_block_attestation_sum[5m])\n/\nrate(operations_per_block_attestation_count[5m])"
    }
   ]
  },
  {
   "title": "Fork Choice Re-org Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "fork_choice_reorg_count" }
   ]
  },
  {
   "title": "Database Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "database_size" }
   ]
  },
  {
   "title": "Head Block Root",
   "type": "graph",
   "description": "Cast as an i64",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "best_beacon_block_root" }
   ]
  },
  {
   "title": "Finalized Root",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "finalized_beacon_block_root" }
   ]
  },
  {
   "title": "Justified Root",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "justified_beacon_block_root" }
   ]
  }
 ]
}