{
 "title": "Database",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "content": "\n# Database Metrics\n\nMetrics collected from a Lighthouse Beacon Node regarding the core key-value database (e.g., LevelDB).\n\nCollected from the `store` crate.\n\n\n\n"
  },
  {
   "title": "On-Disk Database Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "store_disk_db_size" }
   ]
  },
  { "title": "Global", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }, "content": "\n\n" },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 7 },
   "content": "\n### Reads per Minute\n\n\nThe global database reads per minute, expressed as operations and a cumulative bytes value.\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 7 },
   "content": "\n### Writes per Minute\n\n\nThe global database writes per minute, expressed as operations and a cumulative bytes value.\n"
  },
  {
   "title": "DB Read Operations per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Ops per Minute" }
   ],
   "targets": [
    {
     "expr": "increase(store_disk_db_read_count_total [1m])"
    }
   ]
  },
  {
   "title": "DB Read Write (1m avg)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Ops per Minute" }
   ],
   "targets": [
    {
     "expr": "increase(store_disk_db_write_count_total [1m])"
    }
   ]
  },
  {
   "title": "DB Throughput (Read) per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes per Minute" }
   ],
   "targets": [
    {
     "expr": "increase(store_disk_db_read_bytes_total [5m])"
    }
   ]
  },
  {
   "title": "DB Throughput (Write) (1m avg)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes per Minute" }
   ],
   "targets": [
    {
     "expr": "increase(store_disk_db_write_bytes_total [1m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 20 },
   "content": "\n### Beacon state read/write overhead\n\n\nThe encoding/decoding overheads of storing `BeaconState` (excluding action bytes read/write operations).\n"
  },
  {
   "title": "Beacon State Read Overhead",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(store_beacon_state_read_overhead_seconds_sum[5m])\n/\nrate(store_beacon_state_read_overhead_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Beacon State Write Overhead",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(store_beacon_state_write_overhead_seconds_sum[5m])\n/\nrate(store_beacon_state_write_overhead_seconds_count[5m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "content": "\n### Beacon state read/writes\n\n\nNumber of `BeaconState` read/writes in operations and cumulative bytes.\n"
  },
  {
   "title": "Beacon State Reads (Bytes)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "store_beacon_state_read_bytes_total"
    }
   ]
  },
  {
   "title": "Beacon State Writes (Bytes)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "store_beacon_state_write_bytes_total"
    }
   ]
  },
  {
   "title": "Beacon State Reads (Ops)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "sci", "label": "Number of Ops" }
   ],
   "targets": [
    {
     "expr": "store_beacon_state_read_bytes_total"
    }
   ]
  },
  {
   "title": "Beacon State Writes (Ops)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 32 },
   "yaxes": [
    { "format": "sci", "label": "Number of Ops" }
   ],
   "targets": [
    {
     "expr": "store_beacon_state_write_bytes_total"
    }
   ]
  }
 ]
}