{
 "title": "Fork Choice",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Fork Choice Total Times",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(fork_choice_time_sum[5m])\n/\nrate(fork_choice_time_count[5m])"
    }
   ]
  },
  {
   "title": "Fork Choice Find Head Times",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(fork_choice_find_head_time_sum[5m])\n/\nrate(fork_choice_find_head_time_count[5m])"
    }
   ]
  },
  {
   "title": "Fork Choice Process Block Times",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(fork_choice_process_block_time_sum[5m])\n/\nrate(fork_choice_process_block_time_count[5m])"
    }
   ]
  },
  {
   "title": "Fork Choice Process Attestation Times",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(fork_choice_process_attestation_time_sum[5m])\n/\nrate(fork_choice_process_attestation_time_count[5m])"
    }
   ]
  }
 ]
}