{
 "title": "Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Validators",
   "type": "singlestat",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(beacon_head_state_total_validators_total)"
    }
   ]
  },
  {
   "title": "Active Validators",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(beacon_head_state_active_validators_total)"
    }
   ]
  },
  {
   "title": "Shard Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(beacon_head_state_shard_total)"
    }
   ]
  },
  {
   "title": "Seconds per Slot",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(slotclock_slot_time_milliseconds)"
    }
   ]
  },
  {
   "title": "Attestation Processing Times",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_attestation_processing_seconds_sum[5m])\n/\nrate(beacon_attestation_processing_seconds_count[5m])"
    }
   ]
  }
 ]
}