{
 "title": "Processing Stats",
 "description": "Block and Attestation Processing Tracking",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Best Slot",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "best_slot" }
   ]
  },
  {
   "title": "Present Slot",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "present_slot" }
   ]
  },
  {
   "title": "Block Processing Times (5 min Averages)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(block_processing_historgram_sum[5m])\n/\nrate(block_processing_historgram_count[5m])"
    }
   ]
  }
 ]
}