{
 "title": "Summary",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "content": "\n# Lighthouse Metrics\n\nMetrics collected from a Lighthouse Beacon Node.\n\n\n\n"
  },
  {
   "title": "Shard Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(beacon_head_state_shard_total)"
    }
   ]
  },
  {
   "title": "Validator Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(beacon_head_state_total_validators_total)"
    }
   ]
  },
  {
   "title": "Active Validators",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(beacon_head_state_active_validators_total)"
    }
   ]
  },
  {
   "title": "Seconds per Slot",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(slotclock_slot_time_milliseconds)"
    }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    { "expr": "max(slotclock_present_epoch)" }
   ]
  },
  {
   "title": "Slots per Epoch",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "avg(slotclock_slots_per_epoch)" }
   ]
  },
  {
   "title": "Slashed Validators",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(beacon_head_state_slashed_validators_total)"
    }
   ]
  },
  {
   "title": "Withdrawable Validators",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(beacon_head_state_withdrawn_validators_total)"
    }
   ]
  },
  {
   "title": "Current Slot",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    { "expr": "max(slotclock_present_slot)" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 },
   "content": "\n### Consensus\n\nOverview of consensus between nodes.\n\n\n"
  },
  {
   "title": "Slots since Best Block",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Slots" }
   ],
   "targets": [
    {
     "expr": "slotclock_present_slot - beacon_head_state_slot"
    }
   ]
  },
  {
   "title": "Epoch Boundaries since Justification (Min)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Epochs" }
   ],
   "targets": [
    {
     "expr": "slotclock_present_epoch - beacon_head_state_current_justified_epoch"
    }
   ]
  },
  {
   "title": "Epoch Boundaries since Finalization (Min)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Epochs" }
   ],
   "targets": [
    {
     "expr": "slotclock_present_epoch - beacon_head_state_finalized_epoch"
    }
   ]
  },
  {
   "title": "Validator Balances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none", "label": "Total Validator ETH" }
   ],
   "targets": [
    {
     "expr": "beacon_head_state_validator_balances_total / 1000000000"
    }
   ]
  },
  {
   "title": "Finalized Root (hash shown as int)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "sci", "label": "int(hash)" }
   ],
   "targets": [
    {
     "expr": "beacon_head_state_finalized_root"
    }
   ]
  },
  {
   "title": "Total Fork Choice Re-Orgs",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 12 },
   "yaxes": [
    { "format": "none", "label": "Re-Orgs" }
   ],
   "targets": [
    { "expr": "beacon_fork_choice_reorg_total" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 16 },
   "content": "\n### Core BeaconChain Functions\n\nTiming of core `BeaconChain` functions, historical 5-minute averages.\n\n\n"
  },
  {
   "title": "Block Processing Times (5m avg)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_block_processing_seconds_sum[5m])\n/\nrate(beacon_block_processing_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Attestation Processing Times (5m Avg)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_attestation_processing_seconds_sum[5m])\n/\nrate(beacon_attestation_processing_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Fork Choice Times (5m avg)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_fork_choice_seconds_sum[5m])\n/\nrate(beacon_fork_choice_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Update Head Times (5m avg)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_update_head_seconds_sum[5m])\n/\nrate(beacon_update_head_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Block Production Times (5m avg)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_block_production_seconds_sum[5m])\n/\nrate(beacon_block_production_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Block Production Times (5m avg)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_block_production_seconds_sum[5m])\n/\nrate(beacon_block_production_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "State Tree Hash Times (5m avg)",
   "type": "graph",
   "description": "Time taken to calculate the tree hash root of a BeaconState during block processing.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_block_processing_state_root_seconds_sum[5m])\n/\nrate(beacon_block_processing_state_root_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Block Tree Hash Times (5m avg)",
   "type": "graph",
   "description": "Time taken to calculate the tree hash root of a BeaconState during block processing.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_block_processing_block_root_seconds_sum[5m])\n/\nrate(beacon_block_processing_block_root_seconds_count[5m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 28 },
   "content": "\n### Networking (libp2p)\n\n\n\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 28 },
   "content": "\n### HTTP Server\n\nUsed by Prometheus and the RESTful API.\n\n\n\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 28 },
   "content": "\n### Database\n\nStats about the on-disk database (LevelDB)\n\n\n\n"
  },
  {
   "title": "libp2p Connected Peers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "Peers" }
   ],
   "targets": [
    {
     "expr": "libp2p_peer_connected_peers_total"
    }
   ]
  },
  {
   "title": "HTTP Server Request Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_request_duration_seconds_sum[5m])\n/\nrate(http_server_request_duration_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "On-Disk Database Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "store_disk_db_size" }
   ]
  },
  {
   "title": "DB Throughput (Read) per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes per Minute" }
   ],
   "targets": [
    {
     "expr": "increase(store_disk_db_read_bytes_total [5m])"
    }
   ]
  },
  {
   "title": "DB Throughput (Write) (1m avg)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 35 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes per Minute" }
   ],
   "targets": [
    {
     "expr": "increase(store_disk_db_write_bytes_total [1m])"
    }
   ]
  }
 ]
}