{
 "title": "Consensus",
 "time": { "from": "2019-05-28T04:08:03.980Z", "to": "2019-05-28T05:24:17.565Z" },
 "panels": [
  {
   "title": "Best Slot",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "best_slot" }
   ]
  },
  {
   "title": "Present Slot",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "present_slot" }
   ]
  },
  {
   "title": "Validator Count",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "validator_count" }
   ]
  }
 ]
}